import { array, type InferType, object } from 'yup';
import { number, string, union } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), }).defined();

export type A = InferType<typeof A>;

export const B = array().of(union([string(), number(), A,])).defined();

export type B = InferType<typeof B>;
