import { type InferType, mixed, object } from 'yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ a: mixed((input): input is ReferenceError => input instanceof ReferenceError).defined(), }).defined();

export type A = InferType<typeof A>;
