import { literal, undefined as Undefined, union } from '@runtyping/yup'
import { array, type InferType, lazy, type Lazy, object } from 'yup'
import {
  type Student as _Student,
  type Teacher as _Teacher,
} from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/circular-references'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const Teacher: Lazy<_Teacher> = lazy(() =>
  object({
    type: literal('teacher'),
    students: union([array().of(Student).defined(), Undefined()]).optional(),
    reportsTo: union([Teacher, Undefined()]).optional(),
  })
    .defined()
    .default(undefined),
)

export type Teacher = InferType<typeof Teacher>

export const Student: Lazy<_Student> = lazy(() =>
  object({ type: literal('student'), teacher: Teacher })
    .defined()
    .default(undefined),
)

export type Student = InferType<typeof Student>

export const User = union([Student, Teacher])

export type User = InferType<typeof User>
