import { type InferType, object } from 'yup'
import { null as Null, string, union } from '@runtyping/yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = union([Null(), string()])

export type FooType = InferType<typeof FooType>

export const HorseType = object({ a: FooType, b: FooType }).defined()

export type HorseType = InferType<typeof HorseType>
