import { type InferType, mixed } from 'yup'
import {
  A as _A,
  B as _B,
  C as _C,
  E as _E,
} from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/enum'
import { string, union } from '@runtyping/yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = mixed().oneOf(Object.values(_A)).defined()

export type A = InferType<typeof A>

export const B = mixed().oneOf(Object.values(_B)).defined()

export type B = InferType<typeof B>

export const C = mixed().oneOf(Object.values(_C)).defined()

export type C = InferType<typeof C>

export const D = union([
  mixed().oneOf([_C.A3]).defined(),
  mixed().oneOf([_C.B3]).defined(),
])

export type D = InferType<typeof D>

export const F = union([string(), mixed().oneOf([_E.S]).defined()])

export type F = InferType<typeof F>

export const G = union([
  mixed().oneOf([_C.A3]).defined(),
  mixed().oneOf([_C.B3]).defined(),
  mixed().oneOf([_C.C3]).defined(),
  mixed().oneOf([_E.S]).defined(),
])

export type G = InferType<typeof G>
