import { type InferType, mixed } from 'yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = mixed((input): input is Function => typeof input === "function").defined();

export type A = InferType<typeof A>;

export const B = mixed((input): input is Function => typeof input === "function").defined();

export type B = InferType<typeof B>;

export const C = mixed((input): input is Function => typeof input === "function").defined();

export type C = InferType<typeof C>;

export const F = mixed((input): input is Function => typeof input === "function").defined();

export type F = InferType<typeof F>;

export const G = mixed((input): input is Function => typeof input === "function").defined();

export type G = InferType<typeof G>;
