import { type InferType, object, type Schema } from 'yup'
import { number, string, union } from '@runtyping/yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = <T extends any>(T: Schema<T>) => object({ type: T }).defined()

export type A<T> = InferType<ReturnType<typeof A<T>>>

export const B = <T extends string>(T: Schema<T>) =>
  object({ type: T }).defined()

export type B<T extends string> = InferType<ReturnType<typeof B<T>>>

export const C = <T extends any>(T: Schema<T>) => union([string(), T])

export type C<T> = InferType<ReturnType<typeof C<T>>>

export const D = <T extends number>(T: Schema<T>) =>
  object({ type: T }).defined()

export type D<T extends number> = InferType<ReturnType<typeof D<T>>>

export const E = object({ foo: string() }).defined()

export type E = InferType<typeof E>

export const F = <T extends InferType<typeof E>>(T: Schema<T>) =>
  object({ type: T }).defined()

export type F<T extends E> = InferType<ReturnType<typeof F<T>>>

export const G = object({
  abc: A(object({ data: string() }).defined()),
}).defined()

export type G = InferType<typeof G>

export const Test = <T extends any>(T: Schema<T>) =>
  T.concat(object({ count: number() }).defined()).defined()

export type Test<T> = InferType<ReturnType<typeof Test<T>>>

export const Foo = object({
  abc: Test(object({ data: string() }).defined()),
}).defined()

export type Foo = InferType<typeof Foo>
