import { array, type InferType, lazy, type Lazy, object } from 'yup'
import {
  literal,
  null as Null,
  number,
  record,
  string,
  undefined as Undefined,
  union,
} from '@runtyping/yup'
import {
  type JSONSchema7 as _JSONSchema7,
  type JSONSchema7Array as _JSONSchema7Array,
  type JSONSchema7Definition as _JSONSchema7Definition,
  type JSONSchema7Object as _JSONSchema7Object,
  type JSONSchema7Type as _JSONSchema7Type,
} from 'json-schema/index'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const JSONSchema7Definition: Lazy<_JSONSchema7Definition> = lazy(() =>
  union([literal(false), literal(true), JSONSchema7]).default(undefined),
)

export type JSONSchema7Definition = InferType<typeof JSONSchema7Definition>

export const JSONSchema7TypeName = union([
  literal('string'),
  literal('number'),
  literal('boolean'),
  literal('object'),
  literal('integer'),
  literal('array'),
  literal('null'),
])

export type JSONSchema7TypeName = InferType<typeof JSONSchema7TypeName>

export const JSONSchema7Object: Lazy<_JSONSchema7Object> = lazy(() =>
  record(string(), JSONSchema7Type).default(undefined),
)

export type JSONSchema7Object = InferType<typeof JSONSchema7Object>

export const JSONSchema7Array: Lazy<_JSONSchema7Array> = lazy(() =>
  array().of(JSONSchema7Type).defined().default(undefined),
)

export type JSONSchema7Array = InferType<typeof JSONSchema7Array>

export const JSONSchema7Type: Lazy<_JSONSchema7Type> = lazy(() =>
  union([
    Null(),
    string(),
    number(),
    literal(false),
    literal(true),
    JSONSchema7Object,
    JSONSchema7Array,
  ]).default(undefined),
)

export type JSONSchema7Type = InferType<typeof JSONSchema7Type>

export const JSONSchema7: Lazy<_JSONSchema7> = lazy(() =>
  object({
    $id: union([string(), Undefined()]).optional(),
    $ref: union([string(), Undefined()]).optional(),
    $schema: union([string(), Undefined()]).optional(),
    $comment: union([string(), Undefined()]).optional(),
    $defs: union([
      record(string(), JSONSchema7Definition),
      Undefined(),
    ]).optional(),
    type: union([
      literal('string'),
      literal('number'),
      literal('boolean'),
      literal('object'),
      literal('integer'),
      literal('array'),
      literal('null'),
      array().of(JSONSchema7TypeName).defined(),
      Undefined(),
    ]).optional(),
    enum: union([
      array().of(JSONSchema7Type).defined(),
      Undefined(),
    ]).optional(),
    const: union([
      Null(),
      string(),
      number(),
      literal(false),
      literal(true),
      JSONSchema7Object,
      JSONSchema7Array,
      Undefined(),
    ]).optional(),
    multipleOf: union([number(), Undefined()]).optional(),
    maximum: union([number(), Undefined()]).optional(),
    exclusiveMaximum: union([number(), Undefined()]).optional(),
    minimum: union([number(), Undefined()]).optional(),
    exclusiveMinimum: union([number(), Undefined()]).optional(),
    maxLength: union([number(), Undefined()]).optional(),
    minLength: union([number(), Undefined()]).optional(),
    pattern: union([string(), Undefined()]).optional(),
    items: union([
      literal(false),
      literal(true),
      JSONSchema7,
      array().of(JSONSchema7Definition).defined(),
      Undefined(),
    ]).optional(),
    additionalItems: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    maxItems: union([number(), Undefined()]).optional(),
    minItems: union([number(), Undefined()]).optional(),
    uniqueItems: union([literal(false), literal(true), Undefined()]).optional(),
    contains: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    maxProperties: union([number(), Undefined()]).optional(),
    minProperties: union([number(), Undefined()]).optional(),
    required: union([array().of(string()).defined(), Undefined()]).optional(),
    properties: union([
      record(string(), JSONSchema7Definition),
      Undefined(),
    ]).optional(),
    patternProperties: union([
      record(string(), JSONSchema7Definition),
      Undefined(),
    ]).optional(),
    additionalProperties: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    dependencies: union([
      record(
        string(),
        union([
          literal(false),
          literal(true),
          JSONSchema7,
          array().of(string()).defined(),
        ]),
      ),
      Undefined(),
    ]).optional(),
    propertyNames: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    if: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    then: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    else: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    allOf: union([
      array().of(JSONSchema7Definition).defined(),
      Undefined(),
    ]).optional(),
    anyOf: union([
      array().of(JSONSchema7Definition).defined(),
      Undefined(),
    ]).optional(),
    oneOf: union([
      array().of(JSONSchema7Definition).defined(),
      Undefined(),
    ]).optional(),
    not: union([
      literal(false),
      literal(true),
      JSONSchema7,
      Undefined(),
    ]).optional(),
    format: union([string(), Undefined()]).optional(),
    contentMediaType: union([string(), Undefined()]).optional(),
    contentEncoding: union([string(), Undefined()]).optional(),
    definitions: union([
      record(string(), JSONSchema7Definition),
      Undefined(),
    ]).optional(),
    title: union([string(), Undefined()]).optional(),
    description: union([string(), Undefined()]).optional(),
    default: union([
      Null(),
      string(),
      number(),
      literal(false),
      literal(true),
      JSONSchema7Object,
      JSONSchema7Array,
      Undefined(),
    ]).optional(),
    readOnly: union([literal(false), literal(true), Undefined()]).optional(),
    writeOnly: union([literal(false), literal(true), Undefined()]).optional(),
    examples: union([
      Null(),
      string(),
      number(),
      literal(false),
      literal(true),
      JSONSchema7Object,
      JSONSchema7Array,
      Undefined(),
    ]).optional(),
  })
    .defined()
    .default(undefined),
)

export type JSONSchema7 = InferType<typeof JSONSchema7>

export const A = object({ foo: string(), schema: JSONSchema7 }).defined()

export type A = InferType<typeof A>
