import { type InferType, object } from 'yup';
import { literal, number, string } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = object({ bar: string(), foo: string(), }).defined();

export type C = InferType<typeof C>;

export const D = object({ bar: number(), moo: string(), foo: number(), car: string(), }).defined();

export type D = InferType<typeof D>;

export const E = object({ imported: literal(true), }).defined();

export type E = InferType<typeof E>;
