import { type InferType, object } from 'yup'
import { string } from '@runtyping/yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string() }).defined()

export type A = InferType<typeof A>

export const B = object({ bar: string() }).defined()

export type B = InferType<typeof B>

export const C = A.concat(B).defined()

export type C = InferType<typeof C>
