import { type InferType, mixed, object } from 'yup';
import { boolean, literal, number, string } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), bar: number(), [`has spaces`]: boolean(), [`+1`]: boolean(), [`-1`]: boolean(), __underscores__: boolean(), $dollar: boolean(), [`\${escaped template vars}`]: boolean(), }).defined();

export type A = InferType<typeof A>;

export const B = object({ a: A, b: literal("B"), }).defined();

export type B = InferType<typeof B>;

export const C = object({ foo: mixed((input): input is Function => typeof input === "function").defined(), bar: number(), boo: mixed((input): input is Function => typeof input === "function").defined(), }).defined();

export type C = InferType<typeof C>;
