import { literal } from '@runtyping/yup'
import { type InferType } from 'yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = literal('foo')

export type A = InferType<typeof A>

export const B = literal(2)

export type B = InferType<typeof B>

export const C = literal(true)

export type C = InferType<typeof C>
