import { array, type InferType, mixed, object, tuple } from 'yup'
import {
  never as Never,
  record,
  string,
  undefined as Undefined,
  union,
} from '@runtyping/yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({
  testArray: union([
    array().of(Never()).defined(),
    tuple([record(string(), mixed().nullable())]).defined(),
    tuple([
      record(string(), mixed().nullable()),
      record(string(), mixed().nullable()),
    ]).defined(),
    Undefined(),
  ]).optional(),
}).defined()

export type ExampleSchema = InferType<typeof ExampleSchema>
