import { array, type InferType, mixed, object } from 'yup';
import { record, string, undefined as Undefined, union } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({
  testArray: union([array().of(mixed().nullable()).defined().min(2).test('variadic-tuple', "The tuple matches it's variadic length", (data) => record(string(), mixed().nullable()).isValidSync(data![0]) && record(string(), mixed().nullable()).isValidSync(data![1]) && array().of(record(string(), mixed().nullable())).defined().isValidSync(data!.slice(2, undefined))
  ).defined(), Undefined(),]).optional(),
}).defined();

export type ExampleSchema = InferType<typeof ExampleSchema>;
