import { type InferType, mixed, object } from 'yup';
import { number, string } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export namespace A {
  export const B = object({ C: string(), }).defined();

  export type B = InferType<typeof B>;

  export const C = mixed().nullable();

  export type C = InferType<typeof C>;

  export const D = object({ E: number(), }).defined();

  export type D = InferType<typeof D>;
}

export namespace B {
  export namespace C {
    export const D = number();

    export type D = InferType<typeof D>;
  }
}
