import { never as Never, record, string } from '@runtyping/yup';
import { array, type InferType } from 'yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Never();

export type A = InferType<typeof A>;

export const B = record(string(), Never());

export type B = InferType<typeof B>;

export const C = array().of(Never()).defined();

export type C = InferType<typeof C>;
