import {
  null as Null,
  string,
  undefined as Undefined,
  union,
} from '@runtyping/yup'
import { type InferType, object } from 'yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Null()

export type A = InferType<typeof A>

export const B = union([Null(), string()])

export type B = InferType<typeof B>

export const C = object({
  a: Null(),
  b: union([Null(), string()]),
  c: union([Null(), string(), Undefined()]).optional(),
}).defined()

export type C = InferType<typeof C>
