import { type InferType, object } from 'yup';
import { string, undefined as Undefined, union } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: union([string(), Undefined(),]).optional(), }).defined();

export type A = InferType<typeof A>;
