import { array, type InferType, lazy, type Lazy, object } from 'yup';
import { type A as _A, type B as _B } from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/recursive';
import { string, union } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A: Lazy<_A> = lazy(() => object({ recurse: union([string(), A,]), }).defined().default(undefined));

export type A = InferType<typeof A>;

export const B: Lazy<_B> = lazy(() => object({ recurse: array().of(B).defined(), }).defined().default(undefined));

export type B = InferType<typeof B>;
