import { type InferType, object } from 'yup';
import { literal, number, string, undefined as Undefined, union } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({ firstName: string(), lastName: string(), age: union([number(), Undefined(),]).optional(), hairColor: union([literal("black"), literal("brown"), literal("blue"), Undefined(),]).optional(), }).defined();

export type ExampleSchema = InferType<typeof ExampleSchema>;
