import { string } from '@runtyping/yup'
import { type InferType } from 'yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = string()

export type A = InferType<typeof A>
