import { type InferType, tuple } from 'yup';
import { number, string } from '@runtyping/yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = tuple([number(), string(), number(),]).defined();

export type A = InferType<typeof A>;

export const B = tuple([A, A,]).defined();

export type B = InferType<typeof B>;

export const C = tuple([]).defined();

export type C = InferType<typeof C>;
