import { type InferType, mixed } from 'yup';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = mixed().nullable();

export type A = InferType<typeof A>;

export const B = mixed().nullable();

export type B = InferType<typeof B>;
