import {
  A as _A,
  B as _B,
  C as _C,
  D as _D,
  E as _E,
} from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/variadicTuples'
import { array, mixed } from 'yup'
import { boolean, number, string } from '@runtyping/yup'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = array()
  .of(mixed().nullable())
  .defined()
  .min(1)
  .test(
    'variadic-tuple',
    "The tuple matches it's variadic length",
    (data) =>
      string().isValidSync(data![0]) &&
      array().of(string()).defined().isValidSync(data!.slice(1, undefined)),
  )
  .defined()

export type A = _A

export const B = array()
  .of(mixed().nullable())
  .defined()
  .min(2)
  .test(
    'variadic-tuple',
    "The tuple matches it's variadic length",
    (data) =>
      string().isValidSync(data![0]) &&
      number().isValidSync(data![1]) &&
      array().of(number()).defined().isValidSync(data!.slice(2, undefined)),
  )
  .defined()

export type B = _B

export const C = array()
  .of(mixed().nullable())
  .defined()
  .min(1)
  .test(
    'variadic-tuple',
    "The tuple matches it's variadic length",
    (data) =>
      array().of(string()).defined().isValidSync(data!.slice(0, -1)) &&
      number().isValidSync(data![data.length - 1]),
  )
  .defined()

export type C = _C

export const D = array()
  .of(mixed().nullable())
  .defined()
  .min(2)
  .test(
    'variadic-tuple',
    "The tuple matches it's variadic length",
    (data) =>
      string().isValidSync(data![0]) &&
      array().of(string()).defined().isValidSync(data!.slice(1, -1)) &&
      string().isValidSync(data![data.length - 1]),
  )
  .defined()

export type D = _D

export const E = array()
  .of(mixed().nullable())
  .defined()
  .min(5)
  .test(
    'variadic-tuple',
    "The tuple matches it's variadic length",
    (data) =>
      string().isValidSync(data![0]) &&
      number().isValidSync(data![1]) &&
      boolean().isValidSync(data![2]) &&
      array().of(string()).defined().isValidSync(data!.slice(3, -2)) &&
      number().isValidSync(data![data.length - 2]) &&
      boolean().isValidSync(data![data.length - 1]),
  )
  .defined()

export type E = _E
