import { array, number, object, output, string, union } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), });

export type A = output<typeof A>;

export const B = array(union([string(), number(), A,]));

export type B = output<typeof B>;
