import { boolean, output } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = boolean();

export type A = output<typeof A>;
