import { object, optional, type output, record, string, tuple, undefined as Undefined, union, unknown as Unknown } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({ testArray: optional(union([tuple([]), tuple([record(string(), Unknown()),]), tuple([record(string(), Unknown()), record(string(), Unknown()),]), Undefined(),])), });

export type ExampleSchema = output<typeof ExampleSchema>;
