import { any as Any, array, minLength, object, optional, output, record, safeParse, string, superRefine, undefined as Undefined, union, unknown as Unknown } from 'zod/mini';
import { pipeIssues } from '@runtyping/zod-mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({
  testArray: optional(union([array(Any()).check(minLength(2), superRefine((data, ctx) => {
    pipeIssues(safeParse, {
      ctx,
      data: data[0],
      path: 0,
      type: record(string(), Unknown())
    });
    pipeIssues(safeParse, {
      ctx,
      data: data[1],
      path: 1,
      type: record(string(), Unknown())
    });
    pipeIssues(safeParse, {
      ctx,
      data: data.slice(2, undefined),
      path: `2-${2 + data.slice(2, undefined).length}`,
      type: array(record(string(), Unknown()))
    });
  })), Undefined(),])),
});

export type ExampleSchema = output<typeof ExampleSchema>;
