import { array, never as Never, type output, record, string } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Never();

export type A = output<typeof A>;

export const B = record(string(), Never());

export type B = output<typeof B>;

export const C = array(Never());

export type C = output<typeof C>;
