import { object, optional, output, string, undefined as Undefined, union } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: optional(union([string(), Undefined(),])), });

export type A = output<typeof A>;
