import { array, lazy, object, type output, string, union } from 'zod/mini'
import { type $ZodType } from 'zod/v4/core'
import {
  type A as _A,
  type B as _B,
} from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/recursive'

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A: $ZodType<_A> = lazy(() =>
  object({ recurse: union([string(), A]) }),
)

export type A = output<typeof A>

export const B: $ZodType<_B> = lazy(() => object({ recurse: array(B) }))

export type B = output<typeof B>
