import { stringToNumber as stringToNumberTransformer } from '@runtyping/test-type-writers/dist/transformers/stringToNumber';
import { type output, pipe, string, transform } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const TransformStringToNumber = pipe(string(), transform(stringToNumberTransformer));

export type TransformStringToNumber = output<typeof TransformStringToNumber>;
