import { number, output, string, union } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = union([string(), number(),]);

export type C = output<typeof C>;
