import { any as Any, output, unknown as Unknown } from 'zod/mini';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Any();

export type A = output<typeof A>;

export const B = Unknown();

export type B = output<typeof B>;
