import { array, number, object, output, string } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), });

export type A = output<typeof A>;

export const B = array(string().or(number()).or(A));

export type B = output<typeof B>;
