import { instanceof as InstanceOf, object, type output } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ a: InstanceOf(ReferenceError), });

export type A = output<typeof A>;
