import { null as Null, object, type output, string, union } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = union([Null(), string(),]);

export type FooType = output<typeof FooType>;

export const HorseType = object({ a: FooType, b: FooType, });

export type HorseType = output<typeof HorseType>;
