import { null as Null, object, output, string } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = Null().or(string());

export type FooType = output<typeof FooType>;

export const HorseType = object({ a: FooType, b: FooType, });

export type HorseType = output<typeof HorseType>;
