import { literal, nativeEnum, output, string } from 'zod';
import { A as _A, B as _B, C as _C, E as _E } from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/enum';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = nativeEnum(_A);

export type A = output<typeof A>;

export const B = nativeEnum(_B);

export type B = output<typeof B>;

export const C = nativeEnum(_C);

export type C = output<typeof C>;

export const D = literal(_C.A3).or(literal(_C.B3));

export type D = output<typeof D>;

export const F = string().or(literal(_E.S));

export type F = output<typeof F>;

export const G = literal(_C.A3).or(literal(_C.B3)).or(literal(_C.C3)).or(literal(_E.S));

export type G = output<typeof G>;
