import { any as Any, output } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Any();

export type A = output<typeof A>;

export const B = Any();

export type B = output<typeof B>;

export const C = Any();

export type C = output<typeof C>;

export const F = Any();

export type F = output<typeof F>;

export const G = Any();

export type G = output<typeof G>;
