import { instanceof as InstanceOf, type output } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = InstanceOf(Function);

export type A = output<typeof A>;

export const B = InstanceOf(Function);

export type B = output<typeof B>;

export const C = InstanceOf(Function);

export type C = output<typeof C>;

export const F = InstanceOf(Function);

export type F = output<typeof F>;

export const G = InstanceOf(Function);

export type G = output<typeof G>;
