import { intersection, number, object, type output, string, union } from 'zod';
import { type $ZodType } from 'zod/v4/core';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = <T extends any,>(T: $ZodType<T>,) => object({ type: T, });

export type A<T> = output<ReturnType<typeof A<T>>>;

export const B = <T extends string,>(T: $ZodType<T>,) => object({ type: T, });

export type B<T extends string> = output<ReturnType<typeof B<T>>>;

export const C = <T extends any,>(T: $ZodType<T>,) => union([string(), T,]);

export type C<T> = output<ReturnType<typeof C<T>>>;

export const D = <T extends number,>(T: $ZodType<T>,) => object({ type: T, });

export type D<T extends number> = output<ReturnType<typeof D<T>>>;

export const E = object({ foo: string(), });

export type E = output<typeof E>;

export const F = <T extends output<typeof E>,>(T: $ZodType<T>,) => object({ type: T, });

export type F<T extends E> = output<ReturnType<typeof F<T>>>;

export const G = object({ abc: A(object({ data: string(), }),), });

export type G = output<typeof G>;

export const Test = <T extends any,>(T: $ZodType<T>,) => intersection(T, object({ count: number(), }),);

export type Test<T> = output<ReturnType<typeof Test<T>>>;

export const Foo = object({ abc: Test(object({ data: string(), }),), });

export type Foo = output<typeof Foo>;
