import { infer as Infer, number, object, string, ZodType } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = <T extends any,>(T: ZodType<T>,) => object({ type: T, });

export type A<T> = Infer<ReturnType<typeof A<T>>>;

export const B = <T extends string,>(T: ZodType<T>,) => object({ type: T, });

export type B<T extends string> = Infer<ReturnType<typeof B<T>>>;

export const C = <T extends any,>(T: ZodType<T>,) => string().or(T);

export type C<T> = Infer<ReturnType<typeof C<T>>>;

export const D = <T extends number,>(T: ZodType<T>,) => object({ type: T, });

export type D<T extends number> = Infer<ReturnType<typeof D<T>>>;

export const E = object({ foo: string(), });

export type E = Infer<typeof E>;

export const F = <T extends Infer<typeof E>,>(T: ZodType<T>,) => object({ type: T, });

export type F<T extends E> = Infer<ReturnType<typeof F<T>>>;

export const G = object({ abc: A(object({ data: string(), }),), });

export type G = Infer<typeof G>;

export const Test = <T extends any,>(T: ZodType<T>,) => T.and(object({ count: number(), }));

export type Test<T> = Infer<ReturnType<typeof Test<T>>>;

export const Foo = object({ abc: Test(object({ data: string(), }),), });

export type Foo = Infer<typeof Foo>;
