import { boolean, function as func, literal, number, object, output, string, void as Void } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), bar: number(), [`has spaces`]: boolean(), [`+1`]: boolean(), [`-1`]: boolean(), __underscores__: boolean(), $dollar: boolean(), [`\${escaped template vars}`]: boolean(), });

export type A = output<typeof A>;

export const B = object({ a: A, b: literal("B"), });

export type B = output<typeof B>;

export const C = object({ foo: func().args().returns(string()), bar: number(), boo: func().args(string(),).returns(Void()), });

export type C = output<typeof C>;
