import { boolean, instanceof as InstanceOf, literal, number, object, type output, string } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), bar: number(), [`has spaces`]: boolean(), [`+1`]: boolean(), [`-1`]: boolean(), __underscores__: boolean(), $dollar: boolean(), [`\${escaped template vars}`]: boolean(), });

export type A = output<typeof A>;

export const B = object({ a: A, b: literal("B"), });

export type B = output<typeof B>;

export const C = object({ foo: InstanceOf(Function), bar: number(), boo: InstanceOf(Function), });

export type C = output<typeof C>;
