import { object, output, string } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), });

export type A = output<typeof A>;

export const B = object({ bar: string(), });

export type B = output<typeof B>;

export const C = A.and(B);

export type C = output<typeof C>;
