import { object, output, record, string, tuple, undefined as Undefined, unknown as Unknown } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({ testArray: tuple([]).or(tuple([record(string(), Unknown()),])).or(tuple([record(string(), Unknown()), record(string(), Unknown()),])).or(Undefined()).optional(), });

export type ExampleSchema = output<typeof ExampleSchema>;
