import { any as Any, array, object, optional, type output, record, safeParse, string, undefined as Undefined, union, unknown as Unknown } from 'zod';
import { pipeIssues } from '@runtyping/zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({
  testArray: optional(union([array(Any()).min(2).superRefine((data, ctx) => {
    pipeIssues(safeParse, {
      ctx,
      data: data[0],
      path: 0,
      type: record(string(), Unknown())
    });
    pipeIssues(safeParse, {
      ctx,
      data: data[1],
      path: 1,
      type: record(string(), Unknown())
    });
    pipeIssues(safeParse, {
      ctx,
      data: data.slice(2, undefined),
      path: `2-${2 + data.slice(2, undefined).length}`,
      type: array(record(string(), Unknown()))
    });
  }), Undefined(),])),
});

export type ExampleSchema = output<typeof ExampleSchema>;
