import { number, object, type output, string, unknown as Unknown } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export namespace A {
  export const B = object({ C: string(), });

  export type B = output<typeof B>;

  export const C = Unknown();

  export type C = output<typeof C>;

  export const D = object({ E: number(), });

  export type D = output<typeof D>;
}

export namespace B {
  export namespace C {
    export const D = number();

    export type D = output<typeof D>;
  }
}
