import { null as Null, object, optional, type output, string, undefined as Undefined, union } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Null();

export type A = output<typeof A>;

export const B = union([Null(), string(),]);

export type B = output<typeof B>;

export const C = object({ a: Null(), b: union([Null(), string(),]), c: optional(union([Null(), string(), Undefined(),])), });

export type C = output<typeof C>;
