import { null as Null, object, output, string, undefined as Undefined } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Null();

export type A = output<typeof A>;

export const B = Null().or(string());

export type B = output<typeof B>;

export const C = object({ a: Null(), b: Null().or(string()), c: Null().or(string()).or(Undefined()).optional(), });

export type C = output<typeof C>;
