import { infer as Infer, number } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = number();

export type A = Infer<typeof A>;
