import { infer as Infer, object, string, undefined as Undefined } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string().or(Undefined()).optional(), });

export type A = Infer<typeof A>;
