import { literal, number, object, optional, output, string, undefined as Undefined, union } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({ firstName: string(), lastName: string(), age: optional(union([number(), Undefined(),])), hairColor: optional(union([literal("black"), literal("brown"), literal("blue"), Undefined(),])), });

export type ExampleSchema = output<typeof ExampleSchema>;
