import { stringToNumber as stringToNumberTransformer } from '@runtyping/test-type-writers/dist/transformers/stringToNumber';
import { type output, string } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const TransformStringToNumber = string().transform(stringToNumberTransformer);

export type TransformStringToNumber = output<typeof TransformStringToNumber>;
