import { any as Any, infer as Infer, unknown as Unknown } from 'zod';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Any();

export type A = Infer<typeof A>;

export const B = Unknown();

export type B = Infer<typeof B>;
