compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': 'npm:@types/node@*'
      typescript: 'npm:typescript@*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2':
    dependencies:
      typescript: 'npm:typescript@*'
  '@runtyping/test-type-writers@*':
    dependencies:
      runtypes: 'npm:runtypes@*'
      zod: 'npm:zod@^4'
  '@vitest/expect@4.1.2':
    dependencies:
      '@vitest/runner': 'npm:@vitest/runner@4.1.2'
  'fdir@6.5.0':
    dependencies:
      '@types/picomatch': 'npm:@types/picomatch@4.0.3'

yarnPath: .yarn/releases/yarn-4.13.0.cjs
