compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  '@runtyping/test-type-writers@*':
    dependencies:
      runtypes: 'npm:runtypes@*'
      zod: 'npm:zod@*'
  '@vitest/expect@4.0.15':
    dependencies:
      '@vitest/runner': 'npm:@vitest/runner@4.0.15'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
