compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  '@octokit/plugin-retry@4.1.6':
    dependencies:
      '@octokit/request-error': 'npm:@octokit/request-error@4.0.2'
  '@runtyping/test-type-writers@*':
    dependencies:
      runtypes: 'npm:runtypes@*'
      zod: 'npm:zod@*'
  chalk@5.0.0:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'

yarnPath: .yarn/releases/yarn-4.7.0.cjs
