compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "npm:@types/node@*"
      typescript: "npm:typescript@*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    dependencies:
      typescript: "npm:typescript@*"
  "@runtyping/test-type-writers@*":
    dependencies:
      runtypes: "npm:runtypes@*"
      zod: "npm:zod@*"
  "@vitest/expect@4.0.16":
    dependencies:
      "@vitest/runner": "npm:@vitest/runner@4.0.16"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
