import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const Teacher = Joi.object({ type: Joi.any().valid("teacher"), students: Joi.alternatives().try(Joi.array().items(Joi.link('#Student')).required(), Joi.any().forbidden(),).required().optional(), reportsTo: Joi.alternatives().try(Joi.link('#Teacher'), Joi.any().forbidden(),).required().optional(), }).id('Teacher');

export type Teacher = Infer<typeof Teacher>;

export const Student = Joi.object({ type: Joi.any().valid("student"), teacher: Teacher, }).id('Student');

export type Student = Infer<typeof Student>;

export const User = Joi.alternatives().try(Student, Joi.link('#Teacher'),).required();

export type User = Infer<typeof User>;
