import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = Joi.alternatives().try(Joi.any().valid(null).required(), Joi.string().required(),).required();

export type FooType = Infer<typeof FooType>;

export const HorseType = Joi.object({ a: FooType, b: FooType, });

export type HorseType = Infer<typeof HorseType>;
