import { A as _A, B as _B, C as _C, E as _E } from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-0e2292cfef/1/packages/test-type-writers/fixtures/source/enum';
import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.any().valid(...Object.values(_A)).required();

export type A = Infer<typeof A>;

export const B = Joi.any().valid(...Object.values(_B)).required();

export type B = Infer<typeof B>;

export const C = Joi.any().valid(...Object.values(_C)).required();

export type C = Infer<typeof C>;

export const D = Joi.alternatives().try(Joi.any().valid(_C.A3).required(), Joi.any().valid(_C.B3).required(),).required();

export type D = Infer<typeof D>;

export const F = Joi.alternatives().try(Joi.string().required(), Joi.any().valid(_E.S).required(),).required();

export type F = Infer<typeof F>;

export const G = Joi.alternatives().try(Joi.any().valid(_C.A3).required(), Joi.any().valid(_C.B3).required(), Joi.any().valid(_C.C3).required(), Joi.any().valid(_E.S).required(),).required();

export type G = Infer<typeof G>;
