import { type Infer } from '@runtyping/joi';
import Joi from 'joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A;

export type A = Infer<typeof A>;

export const B;

export type B = Infer<typeof B>;

export const C;

export type C = Infer<typeof C>;

export const D;

export type D = Infer<typeof D>;

export const F;

export type F = Infer<typeof F>;

export const G = Joi.object({ abc: A(Joi.object({ data: Joi.string().required(), }),).required(), });

export type G = Infer<typeof G>;

export const Test;

export type Test = Infer<typeof Test>;

export const Foo = Joi.object({ abc: Test(Joi.object({ data: Joi.string().required(), }),).required(), });

export type Foo = Infer<typeof Foo>;
