import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const JSONSchema7 = Joi.link('#import("/Users/john.wright/Workspace/runtyping/.yarn/cache/@types-json-schema-npm-7.0.15-fd16381786-1a3c3e0623.zip/node_modules/@types/json-schema/index").JSONSchema7').id('import("/Users/john.wright/Workspace/runtyping/.yarn/cache/@types-json-schema-npm-7.0.15-fd16381786-1a3c3e0623.zip/node_modules/@types/json-schema/index").JSONSchema7');

export type JSONSchema7 = Infer<typeof JSONSchema7>;

export const A = Joi.object({ foo: Joi.string().required(), schema: JSONSchema7.required(), });

export type A = Infer<typeof A>;
