import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = Joi.object({ bar: Joi.string().required(), foo: Joi.string().required(), });

export type C = Infer<typeof C>;

export const D = Joi.object({ bar: Joi.number().strict().required(), moo: Joi.string().required(), foo: Joi.number().strict().required(), car: Joi.string().required(), });

export type D = Infer<typeof D>;

export const E = Joi.object({ imported: Joi.any().valid(true), });

export type E = Infer<typeof E>;
