import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.object({ foo: Joi.string().required(), bar: Joi.number().strict().required(), [`has spaces`]: Joi.boolean().strict().required(), [`+1`]: Joi.boolean().strict().required(), [`-1`]: Joi.boolean().strict().required(), __underscores__: Joi.boolean().strict().required(), $dollar: Joi.boolean().strict().required(), [`\${escaped template vars}`]: Joi.boolean().strict().required(), });

export type A = Infer<typeof A>;

export const B = Joi.object({ a: A, b: Joi.any().valid("B"), });

export type B = Infer<typeof B>;

export const C = Joi.object({ foo: Joi.func().required(), bar: Joi.number().strict().required(), boo: Joi.func().required(), });

export type C = Infer<typeof C>;
