import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C;

export type C = Infer<typeof C>;
