import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.any().valid("foo");

export type A = Infer<typeof A>;

export const B = Joi.any().valid(2);

export type B = Infer<typeof B>;

export const C = Joi.any().valid(true);

export type C = Infer<typeof C>;
