import { alternatives, array, object } from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({ testArray: alternatives().try(array().ordered), array().ordered.required(), ), array().ordered.required(), .required(), ),,),});

export type ExampleSchema = Infer<typeof ExampleSchema>;
