import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = Joi.object({ testArray: Joi.alternatives().try(, Joi.any().custom((value, helpers) => value === undefined || helpers.error("Value must be undefined")),).optional(), });

export type ExampleSchema = Infer<typeof ExampleSchema>;
