import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export namespace A {
  export const B = Joi.object({ C: Joi.string().required(), });

  export type B = Infer<typeof B>;

  export const C = Joi.any();

  export type C = Infer<typeof C>;

  export const D = Joi.object({ E: Joi.number().strict().required(), });

  export type D = Infer<typeof D>;
}

export namespace B {
  export namespace C {
    export const D = Joi.number().strict().required();

    export type D = Infer<typeof D>;
  }
}
