import { type Infer } from '@runtyping/joi';
import { array } from 'joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A;

export type A = Infer<typeof A>;

export const B;

export type B = Infer<typeof B>;

export const C = array().items();

export type C = Infer<typeof C>;
