import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.any().valid(null).required();

export type A = Infer<typeof A>;

export const B = Joi.alternatives().try(Joi.any().valid(null).required(), Joi.string().required(),).required();

export type B = Infer<typeof B>;

export const C = Joi.object({ a: Joi.any().valid(null).required(), b: Joi.alternatives().try(Joi.any().valid(null).required(), Joi.string().required(),).required(), c: Joi.alternatives().try(Joi.any().valid(null).required(), Joi.string().required(), Joi.any().forbidden(),).required().optional(), });

export type C = Infer<typeof C>;
