import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.object({ recurse: Joi.alternatives().try(Joi.string().required(), Joi.link('#A'),).required(), }).id('A');

export type A = Infer<typeof A>;

export const B = Joi.object({ recurse: Joi.array().items(Joi.link('#B')).required(), }).id('B');

export type B = Infer<typeof B>;
