import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = Joi.object({ firstName: Joi.string().required(), lastName: Joi.string().required(), age: Joi.alternatives().try(Joi.number().strict().required(), Joi.any().forbidden(),).required().optional(), hairColor: Joi.alternatives().try(Joi.any().valid("black"), Joi.any().valid("brown"), Joi.any().valid("blue"), Joi.any().forbidden(),).required().optional(), });

export type ExampleSchema = Infer<typeof ExampleSchema>;
