import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.array().length(3).ordered(Joi.number().strict().required(), Joi.string().required(), Joi.number().strict().required(),).required();

export type A = Infer<typeof A>;

export const B = Joi.array().length(2).ordered(A, A,).required();

export type B = Infer<typeof B>;

export const C = Joi.array().length(0).required();

export type C = Infer<typeof C>;
