import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = Joi.alternatives().try(Joi.string().required(), Joi.number().strict().required(),).required();

export type C = Infer<typeof C>;
