import Joi from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.any();

export type A = Infer<typeof A>;

export const B = Joi.any();

export type B = Infer<typeof B>;
