import Joi, { attempt } from 'joi';
import { type Infer } from '@runtyping/joi';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Joi.array().min(1).custom((data) => [
  attempt(data.at(0), Joi.string().required()),
  ...attempt(data.slice(1, undefined), Joi.array().items(Joi.string().required().optional()))
]).required();

export type A = Infer<typeof A>;

export const B = Joi.array().min(2).custom((data) => [
  attempt(data.at(0), Joi.string().required()),
  attempt(data.at(1), Joi.number().strict().required()),
  ...attempt(data.slice(2, undefined), Joi.array().items(Joi.number().strict().required().optional()))
]).required();

export type B = Infer<typeof B>;

export const C = Joi.array().min(1).custom((data) => [
  ...attempt(data.slice(0, -1), Joi.array().items(Joi.string().required().optional())),
  attempt(data.at(-1), Joi.number().strict().required())
]).required();

export type C = Infer<typeof C>;

export const D = Joi.array().min(2).custom((data) => [
  attempt(data.at(0), Joi.string().required()),
  ...attempt(data.slice(1, -1), Joi.array().items(Joi.string().required().optional())),
  attempt(data.at(-1), Joi.string().required())
]).required();

export type D = Infer<typeof D>;

export const E = Joi.array().min(5).custom((data) => [
  attempt(data.at(0), Joi.string().required()),
  attempt(data.at(1), Joi.number().strict().required()),
  attempt(data.at(2), Joi.boolean().strict().required()),
  ...attempt(data.slice(3, -2), Joi.array().items(Joi.string().required().optional())),
  attempt(data.at(-2), Joi.number().strict().required()),
  attempt(data.at(-1), Joi.boolean().strict().required())
]).required();

export type E = Infer<typeof E>;
