export const Write = Symbol('Write')
export const Import = Symbol('Import')
export const ImportFromSource = Symbol('ImportFromSource')
export const Declare = Symbol('Declare')
export const DeclareAndUse = Symbol('DeclareAndUse')
export const DeclareType = Symbol('DeclareType')
export const Static = Symbol('Static')
