import { array, type InferOutput, number, object, string, union } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), });

export type A = InferOutput<typeof A>;

export const B = array(union([string(), number(), A]));

export type B = InferOutput<typeof B>;
