import { type InferOutput, instance, object } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ a: instance(ReferenceError), });

export type A = InferOutput<typeof A>;
