import { InferOutput, null as Null, object, string, union } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = union([Null(), string()]);

export type FooType = InferOutput<typeof FooType>;

export const HorseType = object({ a: FooType, b: FooType, });

export type HorseType = InferOutput<typeof HorseType>;
