import { function as func, InferOutput } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = func();

export type A = InferOutput<typeof A>;

export const B = func();

export type B = InferOutput<typeof B>;

export const C = func();

export type C = InferOutput<typeof C>;

export const F = func();

export type F = InferOutput<typeof F>;

export const G = func();

export type G = InferOutput<typeof G>;
