import { InferOutput, literal, number, object, string } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = object({ bar: string(), foo: string(), });

export type C = InferOutput<typeof C>;

export const D = object({ bar: number(), moo: string(), foo: number(), car: string(), });

export type D = InferOutput<typeof D>;

export const E = object({ imported: literal(true), });

export type E = InferOutput<typeof E>;
