import { type InferOutput, intersect, object, string } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: string(), });

export type A = InferOutput<typeof A>;

export const B = object({ bar: string(), });

export type B = InferOutput<typeof B>;

export const C = intersect([A, B]);

export type C = InferOutput<typeof C>;
