import { InferOutput, null as Null, object, optional, string, undefined as Undefined, union } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Null();

export type A = InferOutput<typeof A>;

export const B = union([Null(), string()]);

export type B = InferOutput<typeof B>;

export const C = object({ a: Null(), b: union([Null(), string()]), c: optional(union([Null(), string(), Undefined()])), });

export type C = InferOutput<typeof C>;
