import { type InferOutput, number } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = number();

export type A = InferOutput<typeof A>;
