import { type InferOutput, object, optional, string, undefined as Undefined, union } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = object({ foo: optional(union([string(), Undefined()])), });

export type A = InferOutput<typeof A>;
