import { custom, type InferOutput, intersect, record, string } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = intersect([record(string(), string()), custom((data) => !Array.isArray(data), "Unexpected array")]);

export type A = InferOutput<typeof A>;
