import { type InferOutput, literal, number, object, optional, string, undefined as Undefined, union } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = object({ firstName: string(), lastName: string(), age: optional(union([number(), Undefined()])), hairColor: optional(union([literal("black"), literal("brown"), literal("blue"), Undefined()])), });

export type ExampleSchema = InferOutput<typeof ExampleSchema>;
