import { InferOutput, pipe, string, transform } from 'valibot';
import { stringToNumber as stringToNumberTransformer } from '@runtyping/test-type-writers/dist/transformers/stringToNumber';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const TransformStringToNumber = pipe(string(), transform(stringToNumberTransformer));

export type TransformStringToNumber = InferOutput<typeof TransformStringToNumber>;
