import { type InferOutput, number, strictTuple, string } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = strictTuple([number(), string(), number(),]);

export type A = InferOutput<typeof A>;

export const B = strictTuple([A, A,]);

export type B = InferOutput<typeof B>;

export const C = strictTuple([]);

export type C = InferOutput<typeof C>;
