import { any, InferOutput, unknown } from 'valibot';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = any();

export type A = InferOutput<typeof A>;

export const B = unknown();

export type B = InferOutput<typeof B>;
