name: Install

description: Installs node and dependencies

inputs:
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        cache: yarn
        node-version: ${{ inputs.node-version }}
    - shell: bash
      run: yarn --immutable
