import { Array, Number, Object, Parsed, String, Union } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Object({ foo: String, });

export type A = Parsed<typeof A>;

export const B = Array(Union(String, Number, A,));

export type B = Parsed<typeof B>;
