import { Boolean, type Parsed } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Boolean;

export type A = Parsed<typeof A>;
