import { InstanceOf, Record, Static } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Record({ a: InstanceOf(Uint8Array), });

export type A = Static<typeof A>;
