import { Array, Lazy, Literal, Object, Optional, Runtype, Static, Undefined, Union } from 'runtypes';
import { Student as _Student, Teacher as _Teacher } from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/circular-references';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const Teacher: Runtype.Core<_Teacher> = Lazy(() => Object({ type: Literal("teacher"), students: Optional(Union(Array(Student), Undefined,)), reportsTo: Optional(Union(Teacher, Undefined,)), }));

export type Teacher = Static<typeof Teacher>;

export const Student: Runtype.Core<_Student> = Lazy(() => Object({ type: Literal("student"), teacher: Teacher, }));

export type Student = Static<typeof Student>;

export const User = Union(Student, Teacher,);

export type User = Static<typeof User>;
