import { Null, Record, Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = Null.Or(String);

export type FooType = Static<typeof FooType>;

export const HorseType = Record({ a: FooType, b: FooType, });

export type HorseType = Static<typeof HorseType>;
