import { Null, Object, type Parsed, String, Union } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = Union(Null, String,);

export type FooType = Parsed<typeof FooType>;

export const HorseType = Object({ a: FooType, b: FooType, });

export type HorseType = Parsed<typeof HorseType>;
