import { Literal, type Parsed, String, Union } from 'runtypes';
import { A as _A, B as _B, C as _C, E as _E } from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/enum';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Union(...Object.values(_A).map(Literal));

export type A = Parsed<typeof A>;

export const B = Union(...Object.values(_B).map(Literal));

export type B = Parsed<typeof B>;

export const C = Union(...Object.values(_C).map(Literal));

export type C = Parsed<typeof C>;

export const D = Union(Literal(_C.A3), Literal(_C.B3),);

export type D = Parsed<typeof D>;

export const F = Union(String, Literal(_E.S),);

export type F = Parsed<typeof F>;

export const G = Union(Literal(_C.A3), Literal(_C.B3), Literal(_C.C3), Literal(_E.S),);

export type G = Parsed<typeof G>;
