import { Function, Static } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Function;

export type A = Static<typeof A>;

export const B = Function;

export type B = Static<typeof B>;

export const C = Function;

export type C = Static<typeof C>;

export const F = Function;

export type F = Static<typeof F>;

export const G = Function;

export type G = Static<typeof G>;
