import { Function, Parsed } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Function;

export type A = Parsed<typeof A>;

export const B = Function;

export type B = Parsed<typeof B>;

export const C = Function;

export type C = Parsed<typeof C>;

export const F = Function;

export type F = Parsed<typeof F>;

export const G = Function;

export type G = Parsed<typeof G>;
