import { Literal, Number, Object, Parsed, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = Object({ bar: String, foo: String, });

export type C = Parsed<typeof C>;

export const D = Object({ bar: Number, moo: String, foo: Number, car: String, });

export type D = Parsed<typeof D>;

export const E = Object({ imported: Literal(true), });

export type E = Parsed<typeof E>;
