import { Literal, Number, Record, Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = Record({ bar: String, foo: String, });

export type C = Static<typeof C>;

export const D = Record({ bar: Number, moo: String, foo: Number, car: String, });

export type D = Static<typeof D>;

export const E = Record({ imported: Literal(true), });

export type E = Static<typeof E>;
