import { Boolean, Function, Literal, Number, Object, Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Object({ foo: String, bar: Number, [`has spaces`]: Boolean, [`+1`]: Boolean, [`-1`]: Boolean, __underscores__: Boolean, $dollar: Boolean, [`\${escaped template vars}`]: Boolean, });

export type A = Static<typeof A>;

export const B = Object({ a: A, b: Literal("B"), });

export type B = Static<typeof B>;

export const C = Object({ foo: Function, bar: Number, boo: Function, });

export type C = Static<typeof C>;
