import { Record, Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Record({ foo: String, });

export type A = Static<typeof A>;

export const B = Record({ bar: String, });

export type B = Static<typeof B>;

export const C = A.And(B);

export type C = Static<typeof C>;
