import { Literal, Parsed } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Literal("foo");

export type A = Parsed<typeof A>;

export const B = Literal(2);

export type B = Parsed<typeof B>;

export const C = Literal(true);

export type C = Parsed<typeof C>;
