import { Object, Optional, type Parsed, Record, String, Tuple, Undefined, Union, Unknown } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = Object({ testArray: Optional(Union(Tuple(), Tuple(Record(String, Unknown),), Tuple(Record(String, Unknown), Record(String, Unknown),), Undefined,)), });

export type ExampleSchema = Parsed<typeof ExampleSchema>;
