import { Array, Dictionary, Record, Static, String, Undefined, Unknown } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = Record({
  testArray: Array(Unknown).withConstraint<[{ [k: string]: unknown; }, { [k: string]: unknown; }, ...{ [k: string]: unknown; }[]]>(data =>
    data.length >= 2 && Dictionary(Unknown, String).guard(data[0]) && Dictionary(Unknown, String).guard(data[1]) && Array(Dictionary(Unknown, String)).guard(data.slice(2, undefined))
  ).Or(Undefined).optional(),
});

export type ExampleSchema = Static<typeof ExampleSchema>;
