import { Number, Object, Parsed, String, Unknown } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export namespace A {
  export const B = Object({ C: String, });

  export type B = Parsed<typeof B>;

  export const C = Unknown;

  export type C = Parsed<typeof C>;

  export const D = Object({ E: Number, });

  export type D = Parsed<typeof D>;
}

export namespace B {
  export namespace C {
    export const D = Number;

    export type D = Parsed<typeof D>;
  }
}
