import { Array, Never, type Parsed, Record, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Never;

export type A = Parsed<typeof A>;

export const B = Record(String, Never);

export type B = Parsed<typeof B>;

export const C = Array(Never);

export type C = Parsed<typeof C>;
