import { Array, Never, Record, Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Never;

export type A = Static<typeof A>;

export const B = Record(String, Never);

export type B = Static<typeof B>;

export const C = Array(Never);

export type C = Static<typeof C>;
