import { Null, Object, Optional, Static, String, Undefined, Union } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Null;

export type A = Static<typeof A>;

export const B = Union(Null, String,);

export type B = Static<typeof B>;

export const C = Object({ a: Null, b: Union(Null, String,), c: Optional(Union(Null, String, Undefined,)), });

export type C = Static<typeof C>;
