import { Object, Optional, type Parsed, String, Undefined, Union } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Object({ foo: Optional(Union(String, Undefined,)), });

export type A = Parsed<typeof A>;
