import { Dictionary, Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Dictionary(String, String);

export type A = Static<typeof A>;
