import { Array, Lazy, Object, type Parsed, type Runtype, String, Union } from 'runtypes';
import { A as _A, B as _B } from '../../../.yarn/__virtual__/@runtyping-test-type-writers-virtual-f1a80c3a62/1/packages/test-type-writers/fixtures/source/recursive';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A: Runtype.Core<_A> = Lazy(() => Object({ recurse: Union(String, A,), }));

export type A = Parsed<typeof A>;

export const B: Runtype.Core<_B> = Lazy(() => Object({ recurse: Array(B), }));

export type B = Parsed<typeof B>;
