import { Literal, Number, Object, Optional, type Parsed, String, Undefined, Union } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const ExampleSchema = Object({ firstName: String, lastName: String, age: Optional(Union(Number, Undefined,)), hairColor: Optional(Union(Literal("black"), Literal("brown"), Literal("blue"), Undefined,)), });

export type ExampleSchema = Parsed<typeof ExampleSchema>;
