import { Static, String } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const TransformStringToNumber = String;

export type TransformStringToNumber = Static<typeof TransformStringToNumber>;
