import { Parsed, String } from 'runtypes';
import { stringToNumber as stringToNumberTransformer } from '@runtyping/test-type-writers/dist/transformers/stringToNumber';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const TransformStringToNumber = String.withParser(stringToNumberTransformer);

export type TransformStringToNumber = Parsed<typeof TransformStringToNumber>;
