import { Number, Static, String, Union } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = Union(String, Number,);

export type C = Static<typeof C>;
