import { type Parsed, Unknown } from 'runtypes';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Unknown;

export type A = Parsed<typeof A>;

export const B = Unknown;

export type B = Parsed<typeof B>;
