import { failure, success, type, Type, TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = type({
  a: new Type<ReferenceError>(
    'ReferenceError',
    (u): u is ReferenceError => u instanceof ReferenceError,
    (i, c) => i instanceof ReferenceError ? success(i) : failure(i, c, 'not a ReferenceError'),
    (a) => a
  ),
});

export type A = TypeOf<typeof A>;
