import { failure, success, type, Type, TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = type({
  a: new Type<Uint8Array>(
    'Uint8Array',
    (u): u is Uint8Array => u instanceof Uint8Array,
    (i, c) => i instanceof Uint8Array ? success(i) : failure(i, c, 'not a Uint8Array'),
    (a) => a
  ),
});

export type A = TypeOf<typeof A>;
