import { null as Null, string, type, TypeOf, union } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const FooType = union([Null, string,]);

export type FooType = TypeOf<typeof FooType>;

export const HorseType = type({ a: FooType, b: FooType, });

export type HorseType = TypeOf<typeof HorseType>;
