import { Function, TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Function;

export type A = TypeOf<typeof A>;

export const B = Function;

export type B = TypeOf<typeof B>;

export const C = Function;

export type C = TypeOf<typeof C>;

export const F = Function;

export type F = TypeOf<typeof F>;

export const G = Function;

export type G = TypeOf<typeof G>;
