import { literal, number, string, type, TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = type({ bar: string, foo: string, });

export type C = TypeOf<typeof C>;

export const D = type({ bar: number, moo: string, foo: number, car: string, });

export type D = TypeOf<typeof D>;

export const E = type({ imported: literal(true), });

export type E = TypeOf<typeof E>;
