import { intersection, string, type, type TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = type({ foo: string, });

export type A = TypeOf<typeof A>;

export const B = type({ bar: string, });

export type B = TypeOf<typeof B>;

export const C = intersection([A, B,]);

export type C = TypeOf<typeof C>;
