import { number, string, type, type TypeOf, unknown as Unknown } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export namespace A {
  export const B = type({ C: string, });

  export type B = TypeOf<typeof B>;

  export const C = Unknown;

  export type C = TypeOf<typeof C>;

  export const D = type({ E: number, });

  export type D = TypeOf<typeof D>;
}

export namespace B {
  export namespace C {
    export const D = number;

    export type D = TypeOf<typeof D>;
  }
}
