import { validators } from '@runtyping/io-ts';
import { array, record, string, type TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = validators.never;

export type A = TypeOf<typeof A>;

export const B = record(string, validators.never);

export type B = TypeOf<typeof B>;

export const C = array(validators.never);

export type C = TypeOf<typeof C>;
