import { partial, string, TypeOf, undefined as Undefined, union } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = partial({ foo: union([string, Undefined,]), });

export type A = TypeOf<typeof A>;
