import { string, TypeOf } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const TransformStringToNumber = string;

export type TransformStringToNumber = TypeOf<typeof TransformStringToNumber>;
