import { number, string, tuple, type TypeOf } from 'io-ts';
import { validators } from '@runtyping/io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = validators.arrayOfLength<[unknown, unknown, unknown]>(3).pipe(tuple([number, string, number,]));

export type A = TypeOf<typeof A>;

export const B = validators.arrayOfLength<[unknown, unknown]>(2).pipe(tuple([A, A,]));

export type B = TypeOf<typeof B>;

export const C = validators.emptyTuple;

export type C = TypeOf<typeof C>;
