import { number, string, TypeOf, union } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const C = union([string, number,]);

export type C = TypeOf<typeof C>;
