import { type TypeOf, unknown as Unknown } from 'io-ts';

// This file is generated by runtyping (https://github.com/johngeorgewright/runtyping).
// Manual changes might be lost - proceed with caution!
export const A = Unknown;

export type A = TypeOf<typeof A>;

export const B = Unknown;

export type B = TypeOf<typeof B>;
