// this file is AUTOMATICALLY GENERATED by runtypes-generator.
// It includes Runtypes definitions for TypeScript types; so you can validate them at runtime:

import { Array, Record, Static, String } from 'runtypes'

export const Instructions = Array(
  Record({
    targetFile: String,
    sourceTypes: Array(
      Record({
        file: String,
        type: String,
      })
    ),
  })
)
export type Instructions = Static<typeof Instructions>
