name: Pull Request

on:
  pull_request:
    branches: [master]

concurrency:
  cancel-in-progress: true
  group: pr-${{ github.event.pull_request.number }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24, 26]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install
      - uses: ./.github/actions/test
        with:
          node-version: ${{ matrix.node-version }}
